Tracker:AddLocations("locations/rice_beach/course01.json")
Tracker:AddLocations("locations/rice_beach/course02.json")
Tracker:AddLocations("locations/rice_beach/course03.json")
Tracker:AddLocations("locations/rice_beach/course04.json")
Tracker:AddLocations("locations/rice_beach/course05.json")
Tracker:AddLocations("locations/rice_beach/course06.json")

Tracker:AddLocations("locations/mt_teapot/course07.json")
Tracker:AddLocations("locations/mt_teapot/course08.json")
Tracker:AddLocations("locations/mt_teapot/course09.json")
Tracker:AddLocations("locations/mt_teapot/course10.json")
Tracker:AddLocations("locations/mt_teapot/course11.json")
Tracker:AddLocations("locations/mt_teapot/course12.json")
Tracker:AddLocations("locations/mt_teapot/course13.json")

Tracker:AddLocations("locations/sherbet_land/course14.json")
Tracker:AddLocations("locations/sherbet_land/course15.json")
Tracker:AddLocations("locations/sherbet_land/course16.json")
Tracker:AddLocations("locations/sherbet_land/course17.json")
Tracker:AddLocations("locations/sherbet_land/course18.json")
Tracker:AddLocations("locations/sherbet_land/course19.json")

Tracker:AddLocations("locations/stove_canyon/course20.json")
Tracker:AddLocations("locations/stove_canyon/course21.json")
Tracker:AddLocations("locations/stove_canyon/course22.json")
Tracker:AddLocations("locations/stove_canyon/course23.json")
Tracker:AddLocations("locations/stove_canyon/course24.json")
Tracker:AddLocations("locations/stove_canyon/course25.json")

Tracker:AddLocations("locations/ss_tea_cup/course26.json")
Tracker:AddLocations("locations/ss_tea_cup/course27.json")
Tracker:AddLocations("locations/ss_tea_cup/course28.json")
Tracker:AddLocations("locations/ss_tea_cup/course29.json")
Tracker:AddLocations("locations/ss_tea_cup/course30.json")

Tracker:AddLocations("locations/parsley_woods/course31.json")
Tracker:AddLocations("locations/parsley_woods/course32.json")
Tracker:AddLocations("locations/parsley_woods/course33.json")
Tracker:AddLocations("locations/parsley_woods/course34.json")
Tracker:AddLocations("locations/parsley_woods/course35.json")
Tracker:AddLocations("locations/parsley_woods/course36.json")

Tracker:AddLocations("locations/syrup_castle/course37.json")
Tracker:AddLocations("locations/syrup_castle/course38.json")
Tracker:AddLocations("locations/syrup_castle/course39.json")
Tracker:AddLocations("locations/syrup_castle/course40.json")
